### ISSUE TITLE
Missing the correct results

### ISSUE THREAD

**Issue by Toto-Kreusel** [maxfriedmann/meteor-sportbets#16]
The results from the first games are wrong (2nd German League) - something wrong within the OpenLiga import or feed?

**Comment by maxfriedmann** [comment]
Hey Toto, 
Am on vacation right now until the 24th. Will have a look when I am back. Just keep on betting, we can fix that later. 

Cheers, 
Max

**Comment by maxfriedmann** [comment]
Should be fixed within the next release :)
